general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: '3e2d8d81-f839-432f-9b1a-1ea25a3111cf'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
